sudo: required 
services:
 - docker

before_install: 
 - docker build -t anisdhiyaeddine/dockerizedreactapp -f Dockerfile.dev .
scripts: 
 - docker run -e CI=true anisdhiyaeddine/dockerizedreactapp npm run test
deploy: 
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "dockerizedReact"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-769641087123"
  bucket_path: "dockerizedReact"
  on: 
   branch: main
  access_key_id: "$AWS_ACCESS_KEY" 
  secret_access_key: 
   secure: "$AWS_SECRET_KEY"
