sudo: required 
services:
 - docker

before_install: 
 - docker build -t anisdhiyaeddine/dockerizedreactapp -f Dockerfile.dev .
scripts: 
 - docker run -e CI=true anisdhiyaeddine/dockerizedreactapp npm run test

